# Python - Creating Own Data
- create data inside python - list, dictionary, distribution etc
- upload data from laptop - csv, excel, email attachment , etc
- import data from web - git, kaggle,  url etc

In [2]:
import numpy as np
import pandas as pd
import random # create random values

## Step-1 : Setup
- Create data using various Python structures
- ### 20 students - rollno, sname, gender, course, scores, age

In [4]:
# Rollnos - list
rollno = list(range(1, 21))   # 20 students; 1 to 21-1
print(type(rollno), rollno)

<class 'list'> [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [7]:
# Names - (tuple) - immutable, cannot change
sname = ( "Alice", "Bob", "Charlie", "Diana", "Ethan",  "Fiona", "George", "Hannah", "Ian", "Jasmine", \
          "Kevin", "Lily", "Mike", "Nina", "Oscar",  "Priya", "Quinn", "Raj", "Sophia", "Tom")
print(type(sname), list(sname))

<class 'tuple'> ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan', 'Fiona', 'George', 'Hannah', 'Ian', 'Jasmine', 'Kevin', 'Lily', 'Mike', 'Nina', 'Oscar', 'Priya', 'Quinn', 'Raj', 'Sophia', 'Tom']


# structure gets change by use of brackets and the combination
- list [ ]
- tuple ()
- set { }
- 

In [18]:
# Gender - set {unique}
genders_set = {"Male", "Female", 'Male', 'Female'}
gender = [random.choice(list(genders_set)) for _ in rollno]   #create gender values- as size of rollno
print(list(gender))

['Female', 'Male', 'Male', 'Female', 'Female', 'Male', 'Male', 'Female', 'Female', 'Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male']


In [19]:
print('Males -' , gender.count('Male'), ' Females - ' ,  gender.count('Female'))

Males - 13  Females -  7


In [22]:
random.randint(1, 4) # random no between 1 and 4 incl

3

In [24]:
# Course - dictionary : {key:value} pair
courses_dict = {1: "CS", 2: "IT", 3: "AI", 4: "DS"}  # mapping
course = [courses_dict[random.randint(1, 4)] for _ in rollno]
print(list(course))

['DS', 'AI', 'IT', 'AI', 'CS', 'DS', 'AI', 'IT', 'IT', 'AI', 'DS', 'CS', 'CS', 'DS', 'DS', 'DS', 'DS', 'AI', 'IT', 'IT']


In [45]:
x = np.random.normal(loc=50, scale=2, size=5)
print(' Values are - ', x, ' Mean - ' , np.mean(x), ' Std Dev -', np.std(x))
#normal(loc=0.0, scale=1.0, size=None)

 Values are -  [51.0512452  48.95481621 53.52146129 53.7954463  45.67337665]  Mean -  50.59926912928407  Std Dev - 3.030764919035252


In [46]:
np.random.normal(70, 10, len(rollno))  #mean-70, std=10, nos=20

array([69.96397815, 67.59044111, 64.92256395, 70.54003082, 76.86976485,
       63.53789665, 75.15462776, 69.32170031, 67.24482797, 71.49424461,
       78.71554461, 69.63958431, 53.86046011, 55.81434792, 76.14939673,
       65.36319644, 58.90378816, 82.50329797, 67.73574902, 65.330479  ])

In [47]:
?np.clip(np.random.normal(70, 10, len(rollno)), 70, 80)
#https://numpy.org/devdocs/reference/generated/numpy.clip.html

Object `np.clip(np.random.normal(70, 10, len(rollno)), 70, 80)` not found.


In [51]:
a = np.arange(10)
print(a) #array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.clip(a, 2, 6)

[0 1 2 3 4 5 6 7 8 9]


array([2, 2, 2, 3, 4, 5, 6, 6, 6, 6])

In [60]:
# Scores - random normal
# Normally distributed around mean=70, std=10, clipped to 40–100
#score = np.clip(np.random.normal(70, 10, len(rollno)), 45, 95).round(1)
score = np.random.normal(70, 15, len(rollno))
print(score, ':::', np.mean(score), np.std(score))
score = np.clip(score, 50, 95)
print(score)
score = score.round(2)
print(score)
score

[75.9545731  75.85136813 85.72621912 89.53980509 65.70404466 67.70983458
 79.93932077 66.43278226 50.47002432 41.8610656  56.67277182 83.97362842
 75.2856472  67.20273604 73.32318143 75.40528698 78.00188975 88.73927311
 54.58307042 67.29432773] ::: 70.98354252635238 12.443863515375547
[75.9545731  75.85136813 85.72621912 89.53980509 65.70404466 67.70983458
 79.93932077 66.43278226 50.47002432 50.         56.67277182 83.97362842
 75.2856472  67.20273604 73.32318143 75.40528698 78.00188975 88.73927311
 54.58307042 67.29432773]
[75.95 75.85 85.73 89.54 65.7  67.71 79.94 66.43 50.47 50.   56.67 83.97
 75.29 67.2  73.32 75.41 78.   88.74 54.58 67.29]


array([75.95, 75.85, 85.73, 89.54, 65.7 , 67.71, 79.94, 66.43, 50.47,
       50.  , 56.67, 83.97, 75.29, 67.2 , 73.32, 75.41, 78.  , 88.74,
       54.58, 67.29])

In [71]:
# Age - random, integer
age = np.random.randint(19, 31, size=len(rollno)) # 19 to 30
age

array([25, 19, 26, 26, 30, 21, 22, 21, 22, 30, 22, 23, 20, 20, 30, 19, 29,
       25, 19, 29])

In [73]:
#?np.random.randint

In [76]:
print(rollno, '\n', sname,'\n', gender, '\n', course, '\n', score,'\n', age)
#create columns of Data Frame

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] 
 ('Alice', 'Bob', 'Charlie', 'Diana', 'Ethan', 'Fiona', 'George', 'Hannah', 'Ian', 'Jasmine', 'Kevin', 'Lily', 'Mike', 'Nina', 'Oscar', 'Priya', 'Quinn', 'Raj', 'Sophia', 'Tom') 
 ['Female', 'Male', 'Male', 'Female', 'Female', 'Male', 'Male', 'Female', 'Female', 'Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male'] 
 ['DS', 'AI', 'IT', 'AI', 'CS', 'DS', 'AI', 'IT', 'IT', 'AI', 'DS', 'CS', 'CS', 'DS', 'DS', 'DS', 'DS', 'AI', 'IT', 'IT'] 
 [75.95 75.85 85.73 89.54 65.7  67.71 79.94 66.43 50.47 50.   56.67 83.97
 75.29 67.2  73.32 75.41 78.   88.74 54.58 67.29] 
 [25 19 26 26 30 21 22 21 22 30 22 23 20 20 30 19 29 25 19 29]


## Step - 2 : Data Frame
- rows and columns
- Columns - variable names, Rows- data for each student
- Join Columns to Data Frame
- 20 Students Data
- Dictionary : key:value
- pd.DataFrame({ 'key1':values1, 'key2';values})

In [81]:
df = pd.DataFrame({  "rollno": rollno,  "sname": sname,  "gender": gender, "course": course,  "score": score, "age": age})
df.head(2)

rollno  sname  gender course  score  age
0       1  Alice  Female     DS  75.95   25
1       2    Bob    Male     AI  75.85   19

In [82]:
df.tail(2)

rollno   sname gender course  score  age
18      19  Sophia   Male     IT  54.58   19
19      20     Tom   Male     IT  67.29   29

In [83]:
df.shape

(20, 6)

## Larger DF 
- install faker for snames : pip install faker
- https://pypi.org/project/Faker/

In [84]:
#pip install faker

In [85]:
import pandas as pd
import numpy as np
import random
from faker import Faker

In [86]:
# n - no of students
n=1000
fake = Faker()

In [94]:
print(fake.name())
print(fake.address())
print(fake.email())
print(fake.date_of_birth())

Cynthia Castaneda
755 Megan Extension Apt. 740
Moyerstad, ND 95701
amber21@example.com
1927-02-06


In [90]:
print(tuple(fake.name() for _ in rollno[0:20]))

('Jeremy Ross', 'Brad Meyer', 'Roberta Kelley', 'Michael Stevenson', 'Mark Mendoza', 'Krista Wood', 'Mark Howard', 'Michael Parker', 'Sheri Riddle', 'Joseph Knox', 'Julia Jones', 'James Kelly', 'Frank Christian', 'Alexander Lin', 'Tyler Kelly', 'Jonathan Brown', 'Rebecca Greer MD', 'Glen Li', 'Mary Garcia', 'Stephanie Hayes')


In [97]:
n=1001
rollno = list(range(1, n))
sname = tuple(fake.name() for _ in rollno)
genders_set = {"Male", "Female"}
gender = [random.choice(list(genders_set)) for _ in rollno]
courses_dict = {1: "CS", 2: "IT", 3: "AI", 4: "DS"}
course = [courses_dict[random.randint(1, 4)] for _ in rollno]
score = np.clip(np.random.normal(70, 10, len(rollno)), 40, 100).round(1)
age = np.random.randint(18, 25, size=len(rollno))

In [98]:
df2 = pd.DataFrame({    "rollno": rollno,    "sname": sname,    "gender": gender,    "course": course,    "score": score,    "age": age})
df2.shape

(1000, 6)

In [99]:
df2.head()

rollno             sname  gender course  score  age
0       1   Jennifer Gordon  Female     AI   93.2   22
1       2      Amanda Lopez    Male     CS   77.3   24
2       3       Tina Newton  Female     CS   61.6   22
3       4     Alexis Miller    Male     CS   68.1   19
4       5  Rose Johnson DVM    Male     DS   68.5   22

In [102]:
#df2.to_csv('../../data/student160825.csv', index=False)
#f2.to_csv('C:/analytics/data/student160825.csv', index=False)
# the folder and file should be correct

## Own Data
- Synthetic 
- Simulate
- Same value 

## Data from CSV
### file in laptop
- download from : https://catalog.data.gov/dataset/real-estate-sales-2001-2018  (125 MB)
    - listing of all real estate sales with a sales price of $2,000 or greater that occur between October 1 and September 30 of each year. For each sale record, the file includes: town, property address, date of sale, property type (residential, apartment, commercial, industrial or vacant land), sales price, and property assessment. 
- IMF : https://data.imf.org/en/datasets/IMF.STA:QGDP_WCA  (187 KB)
    - This dataset provides a snapshot of the economic activity of the world and selected country aggregates on a quarterly basis. It offers quarterly measurements of Gross Domestic Product (GDP). Quarterly estimates are disseminated on a seasonally adjusted basis.
- Country and capitals; https://ec.europa.eu/eurostat/statistics-explained/images/9/9f/Country_Codes_and_Names.xlsx   (XL)
- max size of excel  the maximum number of rows is 1,048,576 and the maximum number of columns is 16,384 (XFD)
## Online files
- https://raw.githubusercontent.com/DUanalytics/datasets/refs/heads/master/csv/global_world_indicators_2000.csv'

In [106]:
f1='Real_Estate_Sales_2001-2023_GL.csv'
f2='dataset_2025-08-16T11_40_29.251665198Z_DEFAULT_INTEGRATION_IMF.STA_QGDP_WCA_3.0.0.csv'
f3 ='Country_Codes_and_Names.xlsx'
FOLDER ='/Users/du/dup/analytics/data/' #outside git hub : C:/analytics/data
file1 = FOLDER + f1
file2 = FOLDER + f2
file3 = FOLDER + f3
file3 ='/Users/du/dup/analytics/data/Country_Codes_and_Names.xlsx'
print(file1,'\n', file2, '\n', file3)

/Users/du/dup/analytics/data/Real_Estate_Sales_2001-2023_GL.csv 
 /Users/du/dup/analytics/data/dataset_2025-08-16T11_40_29.251665198Z_DEFAULT_INTEGRATION_IMF.STA_QGDP_WCA_3.0.0.csv 
 /Users/du/dup/analytics/data/Country_Codes_and_Names.xlsx


In [105]:
df_f1 = pd.read_csv(file1)
df_f1.shape

/var/folders/z4/8qd93wx14xz1c9qfb_z969wc0000gn/T/ipykernel_10629/223922560.py:1: DtypeWarning: Columns (7,8,9,10,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df_f1 = pd.read_csv(file1)


(1141722, 14)

In [107]:
df_f1.head(2)

Serial Number  List Year Date Recorded     Town         Address  \
0        2020177       2020    04/14/2021  Ansonia   323 BEAVER ST   
1        2020225       2020    05/26/2021  Ansonia  152 JACKSON ST   

   Assessed Value  Sale Amount Sales Ratio Property Type Residential Type  \
0        133000.0     248400.0      0.5354   Residential    Single Family   
1        110500.0     239900.0      0.4606   Residential     Three Family   

  Non Use Code Assessor Remarks OPM remarks                    Location  
0          NaN              NaN         NaN  POINT (-73.06822 41.35014)  
1          NaN              NaN         NaN                         NaN

In [108]:
df_f2 = pd.read_csv(file2)
df_f2.shape

(60, 98)

In [109]:
df_f2.head(2)

DATASET                  SERIES_CODE OBS_MEASURE COUNTRY  \
0  IMF.STA:QGDP_WCA(3.0.0)    G001.B1GQ_S1.POP_PCH_PT.Q   OBS_VALUE   World   
1  IMF.STA:QGDP_WCA(3.0.0)  U142.B1GQ_S1_Q.POP_PCH_PT.Q   OBS_VALUE    Asia   

                                           INDICATOR  \
0        Gross domestic product (GDP), Total economy   
1  Gross domestic product (GDP), Total economy, C...   

                              TYPE_OF_TRANSFORMATION  FREQUENCY  SCALE  \
0  Period-over-preceding period percent change, P...  Quarterly    NaN   
1  Period-over-preceding period percent change, P...  Quarterly    NaN   

   PRECISION  DECIMALS_DISPLAYED  ...   2022-Q4   2023-Q1   2023-Q2   2023-Q3  \
0        NaN                 NaN  ...  0.970324  0.892833  0.464511  0.962598   
1        NaN                 NaN  ...  0.678801  1.386797  1.416312  1.064424   

    2023-Q4   2024-Q1   2024-Q2   2024-Q3   2024-Q4   2025-Q1  
0  0.706613  0.777499  0.246007  0.149742  0.550311  1.879711  
1  0.900656  1.162146  0.926886  1.132581  1.364676  1.141001  

[2 rows x 98 columns]

In [110]:
pd.read_excel(file3).head(4)

AREA    CODE                   COUNTRY NAME
0  European Union (EU)  EU-28   European Union (28 countries)
1  European Union (EU)     BE                         Belgium
2  European Union (EU)     BG                        Bulgaria
3  European Union (EU)     CZ                  Czech Republic

In [115]:
df_f3 = pd.read_excel(file3, skiprows=[1])
# pd.read_excel("students.xlsx", header=1)  # if headers are on 2nd row
df_f3.head(5)

AREA CODE                              COUNTRY NAME
0  European Union (EU)  BE                                    Belgium
1  European Union (EU)  BG                                   Bulgaria
2  European Union (EU)  CZ                             Czech Republic
3  European Union (EU)  DK                                    Denmark
4  European Union (EU)  DE   Germany (including former GDR from 1991)

In [122]:
 pd.read_excel(file3, skiprows=range(1,6)).head()

AREA CODE                              COUNTRY NAME
0  European Union (EU)  DE   Germany (including former GDR from 1991)
1  European Union (EU)  EE                                    Estonia
2  European Union (EU)  IE                                    Ireland
3  European Union (EU)  EL                                     Greece
4  European Union (EU)  ES                                      Spain

In [123]:
# data from Online Resources, downloadable directly
f4 = 'https://raw.githubusercontent.com/DUanalytics/datasets/refs/heads/master/csv/global_world_indicators_2000.csv'
file4 = f4

In [124]:
df_f4 = pd.read_csv(file4)
df_f4.shape

(207, 27)

In [125]:
df_f4.head(2)

Birth Rate  Business Tax Rate  CO2 Emissions Ease of Business (clusters)  \
0        0.02                NaN        87931.0                         Low   
1        0.05                NaN         9542.0                         Low   

  Country/Region  Days to Start Business  Ease of Business  Energy Usage  \
0        Algeria                     NaN               NaN       26998.0   
1         Angola                     NaN               NaN        7499.0   

            GDP  Health Exp % GDP  ...  Mobile Phone Usage  Population 0-14  \
0  5.479006e+10             0.035  ...               0.003            0.342   
1  9.129595e+09             0.034  ...               0.002            0.476   

   Population 15-64  Population 65+  Population Total  Population Urban  \
0             0.619           0.039          31719449             0.599   
1             0.499           0.025          13924930             0.324   

   Region  Tourism Inbound  Tourism Outbound       Year  
0  Africa      102000000.0       193000000.0  12/1/2000  
1  Africa       34000000.0       146000000.0  12/1/2000  

[2 rows x 27 columns]

In [ ]:
#pip install xlrd

In [126]:
f5A= 'https://my.surrey.ac.uk/sites/default/files/2024-12/UOS_RIGO_template_011%20Sample%20tracking%20log%2022Aug23.xlsx'

In [127]:
file5A = f5A
df_f5A = pd.read_excel(file5A)
#df_f5B = pd.read_excel(file5B, engine='xlrd')
df_f5A.shape

(9, 22)

In [128]:
df_f5A.head()

PI:                                         Unnamed: 1  \
0             Study Title:                                                NaN   
1  NHS REC or HTA Licence                                                 NaN   
2   Ethics Application no:                                                NaN   
3             Sample Type   W = Whole Blood   P=Plasma   S=Serum C=PBMC T=...   
4                      NaN                                                NaN   

                 Unnamed: 2                Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0                 Study ID:                       ABC        NaN        NaN   
1  Consent forms location:                        NaN        NaN        NaN   
2         Expiry of ethics:                       NaN        NaN        NaN   
3           Sample Storage   -80, -20, RT, LN2, Other        NaN        NaN   
4                       NaN                       NaN        NaN        NaN   

  Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9  ... Unnamed: 12 Unnamed: 13  \
0        NaN        NaN        NaN        NaN  ...         NaN         NaN   
1        NaN        NaN        NaN        NaN  ...         NaN         NaN   
2        NaN        NaN        NaN        NaN  ...         NaN         NaN   
3        NaN        NaN        NaN        NaN  ...         NaN         NaN   
4        NaN        NaN        NaN        NaN  ...         NaN         NaN   

  Unnamed: 14 Unnamed: 15 Unnamed: 16 Unnamed: 17 Unnamed: 18 Unnamed: 19  \
0         NaN         NaN         NaN         NaN         NaN         NaN   
1         NaN         NaN         NaN         NaN         NaN         NaN   
2         NaN         NaN         NaN         NaN         NaN         NaN   
3         NaN         NaN         NaN         NaN         NaN         NaN   
4         NaN         NaN         NaN         NaN         NaN         NaN   

  Unnamed: 20 Unnamed: 21  
0         NaN         NaN  
1         NaN         NaN  
2         NaN         NaN  
3         NaN         NaN  
4         NaN         NaN  

[5 rows x 22 columns]

## Wiki table
- https://en.wikipedia.org/wiki/List_of_cities_by_GDP

In [129]:
wiki1 = "https://en.wikipedia.org/wiki/List_of_cities_by_GDP"
# read all tables on the page
tables = pd.read_html(wiki1)
print(f"Found {len(tables)} tables")

Found 6 tables


In [130]:
# Identify the correct table
# Often the first is the main list — let's preview the first few tables
for idx, table in enumerate(tables[:3]):
    print(f"\nTable {idx} columns: {table.columns.tolist()}\n")


Table 0 columns: [0, 1]


Table 1 columns: [0, 1]


Table 2 columns: ['City proper/metropolitan area', 'Country/region', 'GDP  (billion US$)', 'Population']



In [131]:
df_wk1 = tables[2]
df_wk1.head()

City proper/metropolitan area Country/region GDP  (billion US$)  \
0    A Coruña metropolitan area          Spain   32.344 (2021)[5]   
1                        Aachen        Germany   27.092 (2021)[5]   
2                       Aalborg        Denmark    30.46 (2022)[5]   
3                        Aarhus        Denmark   53.383 (2022)[5]   
4  Abbotsford, British Columbia         Canada    7.435 (2021)[7]   

            Population  
0  1,121,758 (2021)[6]  
1    556,631 (2021)[6]  
2    591,740 (2022)[6]  
3    913,861 (2022)[6]  
4    205,834 (2021)[8]

In [132]:
df_wk1.shape

(969, 4)

In [133]:
df_wk1.tail()

City proper/metropolitan area Country/region GDP  (billion US$)  \
964                 Zhoushan[325]          China      31.260 (2024)   
965                  Zhuzhou[326]          China      54.797 (2024)   
966                     Zibo[327]          China      68.580 (2024)   
967      Zurich Metropolitan Area    Switzerland  216.392 (2021)[5]   
968                        Zwolle    Netherlands   20.455 (2021)[5]   

              Population  
964     1,174,500 (2024)  
965     3,844,900 (2024)  
966     4,655,350 (2024)  
967  2,123,236 (2021)[6]  
968    377,292 (2021)[6]

In [135]:
df_wk2 = tables[3]
df_wk2.head()

Metropolitan area  GDP (billion USD)     Country  \
0               Valletta             17.603       Malta   
1     City of San Marino              1.540  San Marino   
2  Luxembourg City-Trier             69.450  Luxembourg   
3             Montevideo             53.900     Uruguay   
4                   Riga             27.156      Latvia   

   National GDP (billion USD)  % of national GDP  
0                      19.225             91.563  
1                       1.700             90.872  
2                      86.900             79.925  
3                      70.165             76.819  
4                      39.469             68.803

In [136]:
df_wk4 = tables[4]
df_wk4.head()

City         Wealth  Country/Region
0  New York City    $3 trillion   United States
1         London  $2.7 trillion  United Kingdom
2          Tokyo  $2.5 trillion           Japan
3  San Francisco  $2.3 trillion   United States
4        Beijing  $2.2 trillion           China

### There are different ways to import table in to Python
- create synthetic - store to csv, excel
- import csv, excel
- import from online csv, excel
- import a web , table format; url